# HARMADIK HÉT

## pandas

- A pandas egy NumPy-ra épülő adatfeldolgozó és elemző eszköz. Alapötleteit az R nyelvből vette.
- Alapvető adattípusa a DataFrame (tábla) és a Series (oszlop). Segítségükkel memóriabeli, oszlopalapú adatbázis kezelés valósítható meg.

In [10]:
# A pandas modul importálása pd néven.
import pandas as pd

In [11]:
# A pandas verziószáma.
pd.__version__

'2.2.3'

In [12]:
# DataFrame létrehozása oszlopokból.
# A bemenet egy szótár, ahol a kulcsok az oszlopnevek, az értékek az oszlopok.
df1 = pd.DataFrame({'a': [2, 3, 4], 'b': ['alma', 'körte', 'szilva']})
df1 # A dataframe kiírása

   a       b
0  2    alma
1  3   körte
2  4  szilva

In [13]:
# A df1 objektum típusa.
type(df1)

pandas.core.frame.DataFrame

In [14]:
# Oszlopnevek.
df1.columns

Index(['a', 'b'], dtype='object')

In [15]:
# Iterálás az oszlopneveken.
for c in df1:
    print(c)

a
b

In [16]:
# Sorok száma.
len(df1)

3

In [17]:
# A DataFrame alakja, vagyis dimenziói
df1.shape # (sorok száma, oszlopok száma)

(3, 2)

In [18]:
# Összesítő információ.
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [19]:
# Alapvető oszlopstatisztikák (a numerikus oszlopokról).
df1.describe()

         a
count  3.0
mean   3.0
std    1.0
min    2.0
25%    2.5
50%    3.0
75%    3.5
max    4.0

In [20]:
#ugyanez vízszintesen:
# Alapvető oszlopstatisztikák (a numerikus oszlopokról).
df1.describe().T # T, mint transzponált

   count  mean  std  min  25%  50%  75%  max
a    3.0   3.0  1.0  2.0  2.5  3.0  3.5  4.0

In [21]:
# DataFrame létrehozása sorokból.
# A bemenet szótárak listája, ahol minden szótár egy sort reprezentál.
df2 = pd.DataFrame([{'a': 10, 'b': 'sör'}, {'a': 20}, {'a': 30, 'b': 'bor'}])
df2
# Azért NaN (Not a Number) a b oszlop középsője, mert nem lett megadva neki érték

    a    b
0  10  sör
1  20  NaN
2  30  bor

In [22]:
# Minden DataFrame-hez (és Series-hez) tartozik index.
# Alapértelmezés szerint az index 0-tól induló, 1-esével növekedő sorszám.
df2.index
# Fontos, hogy az 0 már létezik, de a 3-mas index out of range

RangeIndex(start=0, stop=3, step=1)

In [23]:
# Ez természetesen felülbírálható, másfajta indexet is használhatunk.
df2 = pd.DataFrame(
    [{'a': 10, 'b': 'sör'}, {'a': 20}, {'a': 30, 'b': 'bor'}],
    index=['xxx', 'yyy', 4242] # Ha itt kiveszünk egy értéket, akkor hibát dob
)
df2

       a    b
xxx   10  sör
yyy   20  NaN
4242  30  bor

In [24]:
# Series létrehozása index megadása nélkül.
se1 = pd.Series([20, 30, 40])
se1

0    20
1    30
2    40
dtype: int64

In [25]:
# Az eredmény típusa.
type(se1)

pandas.core.series.Series

In [26]:
# Series létrehozása index megadásával.
pd.Series([20, 30, 40], index=['a', 'b', 'c'])

a    20
b    30
c    40
dtype: int64

In [27]:
# DataFrame-ből [] operátorral lehet kiválasztani oszlopot.
df1 = pd.DataFrame({'xx': [20, 30, 40], 'yy': ['a', 'b', 'c']})
df1

   xx yy
0  20  a
1  30  b
2  40  c

In [ ]:
df1['xx'] # Az xx kulcshoz tartozó érték (lista) kiírása

0    20
1    30
2    40
Name: xx, dtype: int64

In [25]:
# ...illetve ha az oszlop neve érvényes azonosítónév, akkor . operátorral is.
df1.xx

0    20
1    30
2    40
Name: xx, dtype: int64

In [ ]:
# Több oszlop kiválasztása.
df1[['yy', 'xx', 'yy']] # Előfordulhat ismétlődés

  yy  xx yy
0  a  20  a
1  b  30  b
2  c  40  c

In [32]:
# Ha 1 elemű listával indexelünk, akkor az eredmény DataFrame típusú.
df1[['xx']]

   xx
0  20
1  30
2  40

In [28]:
df1['xx']

0    20
1    30
2    40
Name: xx, dtype: int64

In [33]:
df1

   xx yy
0  20  a
1  30  b
2  40  c

In [34]:
# Sor(ok)kiválasztása DataFrame-ből.
df2 = pd.DataFrame({'xx': [20, 30, 40], 'yy': ['a', 'b', 'c']}, index=['sör', 'bor', 'rum'])
df2

     xx yy
sör  20  a
bor  30  b
rum  40  c

In [35]:
df2.loc['sör']

xx    20
yy     a
Name: sör, dtype: object

In [36]:
df2.loc[['sör', 'rum']]

     xx yy
sör  20  a
rum  40  c

In [ ]:
# ...index alapján is lehet sort kiválasztani
df2.iloc[ 1 ]

xx    30
yy     b
Name: bor, dtype: object

In [38]:
df2.iloc[[0, 2, 0, 2]]

     xx yy
sör  20  a
rum  40  c
sör  20  a
rum  40  c

In [39]:
# Elem kiválasztása Series-ből.
se2 = pd.Series([20, 30, 40], index=['a', 'b', 'c'])
se2

a    20
b    30
c    40
dtype: int64

In [40]:
se2['b']

np.int64(30)

In [41]:
# Nyers adattartalom elérése.
df2.values

array([[20, 'a'],
       [30, 'b'],
       [40, 'c']], dtype=object)

In [42]:
se2.values

array([20, 30, 40])

### [Kiválasztás](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html)(Select)

In [28]:
# Hozzunk létre egy példa DataFrame-et!
df = pd.DataFrame([
    {'tanuló': 'Gipsz Jakab',  'tantárgy': 'Matematika',  'osztályzat': 5},
    {'tanuló': 'Gipsz Jakab',  'tantárgy': 'Testnevelés', 'osztályzat': 2},
    {'tanuló': 'Bank Aranka',  'tantárgy': 'Matematika',  'osztályzat': 3},
    {'tanuló': 'Bank Aranka',  'tantárgy': 'Matematika',  'osztályzat': 5},
    {'tanuló': 'Bank Aranka',  'tantárgy': 'Testnevelés', 'osztályzat': 4},
    {'tanuló': 'Rontó Róbert', 'tantárgy': 'Matematika',  'osztályzat': 1},
    {'tanuló': 'Rontó Róbert', 'tantárgy': 'Matematika',  'osztályzat': 2},
    {'tanuló': 'Rontó Róbert', 'tantárgy': 'Testnevelés', 'osztályzat': 5},
])
df

         tanuló     tantárgy  osztályzat
0   Gipsz Jakab   Matematika           5
1   Gipsz Jakab  Testnevelés           2
2   Bank Aranka   Matematika           3
3   Bank Aranka   Matematika           5
4   Bank Aranka  Testnevelés           4
5  Rontó Róbert   Matematika           1
6  Rontó Róbert   Matematika           2
7  Rontó Róbert  Testnevelés           5

In [29]:
# Logikai feltétel oszlop.
df['tantárgy'] == 'Matematika'

0     True
1    False
2     True
3     True
4    False
5     True
6     True
7    False
Name: tantárgy, dtype: bool

In [ ]:
df[df['tantárgy'] == 'Matematika'] # A df-ből lekérdezi azokat, amikre a feltétel igaz

         tanuló    tantárgy  osztályzat
0   Gipsz Jakab  Matematika           5
2   Bank Aranka  Matematika           3
3   Bank Aranka  Matematika           5
5  Rontó Róbert  Matematika           1
6  Rontó Róbert  Matematika           2

In [46]:
# Gipsz Jakab összes osztályzata.
df[df['tanuló'] == 'Gipsz Jakab'] # A df-ből lekérdezi azokat, amikre a feltétel igaz

        tanuló     tantárgy  osztályzat
0  Gipsz Jakab   Matematika           5
1  Gipsz Jakab  Testnevelés           2

In [ ]:
# Az 1-esnél jobb és 5-ösnél rosszabb osztályzatok.
df[(df['osztályzat'] > 1) & (df['osztályzat'] < 5)]

         tanuló     tantárgy  osztályzat
1   Gipsz Jakab  Testnevelés           2
2   Bank Aranka   Matematika           3
4   Bank Aranka  Testnevelés           4
6  Rontó Róbert   Matematika           2

### [Csoportosítás](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html)(Groupby)

Pandasban a csoportosítás folyamata az alábbi lépésekből áll:
- Az adatok felosztása (split) csoportokra, valamilyen feltétel alapján.
- Valamely függvény alkalmazása (apply) az egyes csoportokra külön-külön.
- Az eredmények kombinálása (combine) egy adatszerkezetbe.

Ezek közül a felosztás a legegyszerűbb. A felosztás kritériuma általában egy oszlopban (vagy oszlop kombinációban) található érték. A függvényalkalmazás lehet aggregáló jellegű (pl. csoportonkénti elemszám, összeg, átlag, minimum, maximum, első rekord, utolsó rekord) vagy egyéb (pl. csoportonkénti standardizálás, adathiány kitöltés vagy szűrés). A kombinálási lépés az aggregáló típusú függvények esetén automatikusan lefut, egyéb esetekben a programozónak kell kezdeményeznie.

In [48]:
# Használjuk az előző DataFrame-et!
df

         tanuló     tantárgy  osztályzat
0   Gipsz Jakab   Matematika           5
1   Gipsz Jakab  Testnevelés           2
2   Bank Aranka   Matematika           3
3   Bank Aranka   Matematika           5
4   Bank Aranka  Testnevelés           4
5  Rontó Róbert   Matematika           1
6  Rontó Róbert   Matematika           2
7  Rontó Róbert  Testnevelés           5

In [49]:
# Csoportosítás tantárgyak szerint.
gb = df.groupby('tantárgy')

In [50]:
# Az eredmény típusa.
type(gb)

pandas.core.groupby.generic.DataFrameGroupBy

In [51]:
# Hány rekord tartozik az egyes tantárgyakhoz?
gb.size()

tantárgy
Matematika     5
Testnevelés    3
dtype: int64

In [52]:
# Ugyanez az átmeneti gb objektum használata nélkül.
df.groupby('tantárgy').size()

tantárgy
Matematika     5
Testnevelés    3
dtype: int64

In [ ]:
# Tantárgyankénti átlag.
df.groupby('tantárgy')['osztályzat'].mean() # Csoportosítunk tantárgyak szerint, majd ezen az osztályzatokat vesszük. Ezen használjuk a mean-t

tantárgy
Matematika     3.200000
Testnevelés    3.666667
Name: osztályzat, dtype: float64

In [55]:
# Tantárgyankénti átlag minden tanulóhoz.
df.groupby(['tanuló', 'tantárgy'])['osztályzat'].mean() # Vesszük a tanulókat, azokon belül a tantárgyakat, majd ezen az osztályzatokat.

tanuló        tantárgy
Bank Aranka   Matematika     4.0
              Testnevelés    4.0
Gipsz Jakab   Matematika     5.0
              Testnevelés    2.0
Rontó Róbert  Matematika     1.5
              Testnevelés    5.0
Name: osztályzat, dtype: float64

In [56]:
type(df.groupby(['tanuló', 'tantárgy'])['osztályzat'].mean())

pandas.core.series.Series

In [58]:
# Az index átalakítása két hagyományos oszloppá.
df.groupby(['tanuló', 'tantárgy'])['osztályzat'].mean().reset_index()

         tanuló     tantárgy  osztályzat
0   Bank Aranka   Matematika         4.0
1   Bank Aranka  Testnevelés         4.0
2   Gipsz Jakab   Matematika         5.0
3   Gipsz Jakab  Testnevelés         2.0
4  Rontó Róbert   Matematika         1.5
5  Rontó Róbert  Testnevelés         5.0

### Gyakorlás
A pl.txt fájl az angol Premier League 2011-12-es szezonjának eredményeit tartalmazza:

- 1. oszlop: forduló
- 2. oszlop: hazai csapat neve
- 3. oszlop: vendégcsapat neve
- 4. oszlop: hazai csapat góljainak száma
- 5. oszlop: vendégcsapat góljainak száma

In [ ]:
# Töltsük be a pl.txt fájl adatait DataFrame-be!
names = ['forduló', 'hazai csapat', 'vendégcsapat', 'hazai gól', 'vendég gól'] # ezek lesznek az oszlopnevek
pl = pd.read_csv('datafiles/pl.txt', sep='\t', skiprows=6, names=names) # tabulátor az elválasztás, az első 6 sort átugorjuk
pl

,forduló,hazai csapat,vendégcsapat,hazai gól,vendég gól
0,1,Blackburn Rovers,Wolverhampton Wanderers,1,2
1,1,Fulham FC,Aston Villa,0,0
2,1,Liverpool FC,Sunderland AFC,1,1
3,1,Queens Park Rangers,Bolton Wanderers,0,4
4,1,Wigan Athletic,Norwich City,1,1
...,...,...,...,...,...
375,38,Sunderland AFC,Manchester United,0,1
376,38,Swansea City,Liverpool FC,1,0
377,38,Tottenham Hotspur,Fulham FC,2,0
378,38,West Bromwich Albion,Arsenal FC,2,3
379,38,Wigan Athletic,Wolverhampton Wanderers,3,2


### Feladatok
1. Kérjük le az alapvető információkat (len, shape, .columns, .info(), .describe()).
2. Adjuk meg, hogy összesen hány hazai és hány vendég gól született. (.sum())
3. Adjunk hozzá egy új oszlopot, amely a gólok (hazai+vendég) tartalmazza.
4. Határozzuk meg, hogy meccsenként átlagosan hány gól született. (.mean())
5. A mérkőzések hány százalékán esett gól?
6. elyik mérkőzésen esett a legtöbb gól?
7. Tekintsük a Liverpool FC mérkőzéseit.
    - Átlagosan hány gólt szereztek hazai pályán és hányat kaptak?
    - Hány hazai meccset nyertek meg?
    - Idegenben mennyi volt a legtöbb góljuk?
8. Melyik fordulóban hány gól esett?
9. Melyik fordulóban esett a legtöbb gól?
10. Melyik fordulóban mennyi volt az átlagos mérkőzésenkénti gólszám?
11. Írjuk ki a tíz leggólgazdagabb fordulót, gólszámokkal együtt!
12. Határozzuk meg, hogy a bajnokság végén melyik csapatnak hány pontja volt (győzelem 3 pont, dönttelen 1 pont, vereség 0 pont).

In [63]:
# 1. Az alapvető információk (len, shape, .columns, .info(), .describe()):

len(pl)

pl.shape

pl.columns

pl.info()

pl.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   forduló       380 non-null    int64
 1   hazai csapat  380 non-null    object
 2   vendégcsapat  380 non-null    object
 3   hazai gól     380 non-null    int64
 4   vendég gól    380 non-null    int64
dtypes: int64(3), object(2)
memory usage: 15.0+ KB

          forduló   hazai gól  vendég gól
count  380.000000  380.000000  380.000000
mean    19.500000    1.589474    1.215789
std     10.980313    1.331531    1.204987
min      1.000000    0.000000    0.000000
25%     10.000000    1.000000    0.000000
50%     19.500000    1.000000    1.000000
75%     29.000000    2.000000    2.000000
max     38.000000    8.000000    6.000000

In [ ]:
# 2. Adjuk meg, hogy összesen hány hazai és hány vendég gól született. (.sum())

print(pl['hazai gól'].sum())

print(pl['vendég gól'].sum())

# print nélkül csak a legutolsót írja ki, ami nem elég

604
462

In [69]:
# 3. Adjunk hozzá egy új oszlopot, amely a gólokat (hazai+vendég) tartalmazza.

pl['gólok'] = pl['hazai gól'] + pl['vendég gól']
pl

,forduló,hazai csapat,vendégcsapat,hazai gól,vendég gól,gólok
0,1,Blackburn Rovers,Wolverhampton Wanderers,1,2,3
1,1,Fulham FC,Aston Villa,0,0,0
2,1,Liverpool FC,Sunderland AFC,1,1,2
3,1,Queens Park Rangers,Bolton Wanderers,0,4,4
4,1,Wigan Athletic,Norwich City,1,1,2
...,...,...,...,...,...,...
375,38,Sunderland AFC,Manchester United,0,1,1
376,38,Swansea City,Liverpool FC,1,0,1
377,38,Tottenham Hotspur,Fulham FC,2,0,2
378,38,West Bromwich Albion,Arsenal FC,2,3,5
379,38,Wigan Athletic,Wolverhampton Wanderers,3,2,5

In [70]:
# 4. Határozzuk meg, hogy meccsenként átlagosan hány gól született. (.mean())

pl['gólok'].mean()

np.float64(2.805263157894737)

In [72]:
# 5. A mérkőzések hány százalékán esett gól?

len(pl[ pl['gólok'] > 0]) / len(pl) * 100 # Százalékszámítás: (volt gól / nem volt gól) * 100

# másképp:
(pl['gólok'] > 0).sum() / len(pl) *100

np.float64(92.89473684210526)

In [74]:
# 6. Melyik mérkőzésen esett a legtöbb gól?

pl[ pl['gólok'] == pl['gólok'].max() ] # Ahol a gólok száma egyenlő a legtöbb góllal

# másképp:
pl.iloc[pl['gólok'].idxmax()]

forduló                         3
hazai csapat    Manchester United
vendégcsapat           Arsenal FC
hazai gól                       8
vendég gól                      2
gólok                          10
Name: 29, dtype: object

In [78]:
# 7. Tekintsük a Liverpool FC mérkőzéseit.
# A. Átlagosan hány gólt szereztek hazai pályán és hányat kaptak?
szerzett = pl[ pl['hazai csapat'] == 'Liverpool FC']['hazai gól'].mean()
kapott = pl[ pl['hazai csapat'] == 'Liverpool FC']['vendég gól'].mean()
print(f'Átlagosan szerzett: {szerzett}, átlagosan kapott: {kapott} ')

# B. Hány hazai meccset nyertek meg?
# megszámoljuk, hogy a Liverpool FC meccseinél hány olyan van, 
# ahol a hazai gólok száma nagyobb vendég gólok számánál.
(pl[ pl['hazai csapat'] == 'Liverpool FC']['hazai gól'] > pl[ pl['hazai csapat'] == 'Liverpool FC']['vendég gól']).sum()


# másképp: 
# a hazai győzelmek közül megszámoljuk, hogy hány olyan volt,
# amikor a Liverpool FC volt a hazai csapat
feltetel1 = (pl['hazai gól'] > pl['vendég gól'])
feltetel2 = (pl['hazai csapat'] == 'Liverpool FC')
len( pl[ feltetel1 & feltetel2] )

# C. Idegenben mennyi volt a legtöbb góljuk?
pl[ pl['vendégcsapat'] == 'Liverpool FC']['vendég gól'].max()

Átlagosan szerzett: 1.263157894736842, átlagosan kapott: 0.8421052631578947

np.int64(3)

In [79]:
# 8. Melyik fordulóban hány gól esett?
pl.groupby('forduló')['gólok'].sum()

forduló
1     20
2     23
3     31
4     22
5     38
6     27
7     34
8     32
9     31
10    39
11    31
12    30
13    25
14    30
15    30
16    18
17    31
18    19
19    26
20    29
21    22
22    35
23    23
24    31
25    36
26    30
27    24
28    17
29    27
30    25
31    35
32    23
33    29
34    28
35    22
36    35
37    26
38    32
Name: gólok, dtype: int64

In [80]:
# 9. Melyik fordulóban esett a legtöbb gól?

pl.groupby('forduló')['gólok'].sum().idxmax()

np.int64(10)

In [83]:
# 10. Melyik fordulóban mennyi volt az átlagos mérkőzésenkénti gólszám?

pl.groupby('forduló')['gólok'].mean()

forduló
1     2.0
2     2.3
3     3.1
4     2.2
5     3.8
6     2.7
7     3.4
8     3.2
9     3.1
10    3.9
11    3.1
12    3.0
13    2.5
14    3.0
15    3.0
16    1.8
17    3.1
18    1.9
19    2.6
20    2.9
21    2.2
22    3.5
23    2.3
24    3.1
25    3.6
26    3.0
27    2.4
28    1.7
29    2.7
30    2.5
31    3.5
32    2.3
33    2.9
34    2.8
35    2.2
36    3.5
37    2.6
38    3.2
Name: gólok, dtype: float64

In [ ]:
# 11. Írjuk ki a tíz leggólgazdagabb fordulót, gólszámokkal együtt!

pl.groupby('forduló')['gólok'].sum().sort_values(ascending=False)[:10] # ascending: növekvő

forduló
10    39
5     38
25    36
31    35
22    35
36    35
7     34
38    32
8     32
11    31
Name: gólok, dtype: int64

In [86]:
# 12. Határozzuk meg, hogy a bajnokság végén melyik csapatnak hány pontja volt (győzelem 3 pont, döntetlen 1 pont, vereség 0 pont).

# Minden egyes meccsre kiszámítjuk, hogy az adott meccsen hány hazai és 
# hány vendégpont született. Majd minden egyes csapatra kiszámítjuk, hogy
# hány pontot szerzett hazai csapatként és mennyit vendégként. Végül ezek
# összege adja a végső pontszámot.
#
# A '.sort_values(ascending=False)' paranccsal a pontszámok szerint csökkenő 
# sorrendbe rendezünk. Enélkül ábécé szerinti sorrendet kapunk.
#


pl['hazai pont'] = ( (pl['hazai gól'] > pl['vendég gól'] ) *3 + 
                     (pl['hazai gól'] == pl['vendég gól'] ) *1 )

pl['idegenbeli pont'] = ( (pl['hazai gól'] < pl['vendég gól'] ) *3 + 
                          (pl['hazai gól'] == pl['vendég gól'] ) *1 )

pontszám = (pl.groupby('hazai csapat')['hazai pont'].sum() + 
            pl.groupby('vendégcsapat')['idegenbeli pont'].sum() 
           ).sort_values(ascending=False)

pontszám

hazai csapat
Manchester City            89
Manchester United          89
Arsenal FC                 70
Tottenham Hotspur          69
Newcastle United           65
Chelsea FC                 64
Everton FC                 56
Liverpool FC               52
Fulham FC                  52
Norwich City               47
West Bromwich Albion       47
Swansea City               47
Sunderland AFC             45
Stoke City                 45
Wigan Athletic             43
Aston Villa                38
Queens Park Rangers        37
Bolton Wanderers           36
Blackburn Rovers           31
Wolverhampton Wanderers    25
dtype: int64